### ISSUE TITLE
.Net Core & Roadmap

### ISSUE THREAD

**Issue by JosepBalague** [n9/pdfclown#2]
Any plan to add .NET Core support?

Your roadmap in https://pdfclown.org/development/roadmap/ seems to be outdated. 0.2.0 version is estimated to be released at July 2015 and Nuget has 0.1.2 version. Something is wrong. Please can you publish real roadmap?

Cheers

**Comment by n9** [comment]
I am not the pdfclown developer, you should contact the original author here: https://pdfclown.org/resources/support/ or https://pdfclown.org/contact-us/.
